Remove not needed Cabal-syntax package
Seems like Cabal-syntax is re-exported from Cabal itself and this is
causing tons of these errors:

  Reading Haskell configuration failed with exit code 1 and output:

  /home/ricardo/.emacs.d/elpa/flycheck-haskell-20230706.1439/get-cabal-configuration.hs:118:1: error:
      Ambiguous module name ‘Distribution.ModuleName’:
        it was found in multiple packages:
        Cabal-3.6.3.0 Cabal-syntax-3.8.1.0
      |
  118 | import Distribution.ModuleName (ModuleName)
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  /home/ricardo/.emacs.d/elpa/flycheck-haskell-20230706.1439/get-cabal-configuration.hs:119:1: error:
      Ambiguous module name ‘Distribution.ModuleName’:
        it was found in multiple packages:
        Cabal-3.6.3.0 Cabal-syntax-3.8.1.0
      |
  119 | import qualified Distribution.ModuleName as ModuleName
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  /home/ricardo/.emacs.d/elpa/flycheck-haskell-20230706.1439/get-cabal-configuration.hs:120:1: error:
      Ambiguous module name ‘Distribution.PackageDescription’:
        it was found in multiple packages:
        Cabal-3.6.3.0 Cabal-syntax-3.8.1.0
      |
  120 | import Distribution.PackageDescription ()
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^